name: Tester

on:
  push:
  pull_request:
  release:
    types: [published]

jobs:
  example1:
    runs-on: ubuntu-latest
    continue-on-error: true
    container:
      image: docker://turtlecoincore/ci:crypto-x64-linux
      options: --entrypoint /bin/bash
    steps:
      - name: Clone
        uses: actions/checkout@v2

      - name: Run Test
        run: |
          file /bin/bash

  example2:
    runs-on: ubuntu-latest
    continue-on-error: true
    container:
      image: docker://turtlecoincore/ci:crypto-ia32-linux
      options: --entrypoint /bin/bash
    steps:
      - name: Clone
        uses: actions/checkout@v2

      - name: Run Test
        run: |
          file /bin/bash

  example3:
    runs-on: ubuntu-latest
    continue-on-error: true
    container:
      image: docker://turtlecoincore/ci:crypto-arm64v8-linux
      options: --entrypoint /bin/bash
    steps:
      - name: Clone
        uses: actions/checkout@v2

      - name: Run Test
        run: |
          file /bin/bash
