name: Tester

on:
  push:
  pull_request:
  release:
    types: [published]

jobs:
  example:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run test
        uses: docker://turtlecoincore/ci:crypto-ia32-linux
        with:
          entrypoint: /bin/bash
          args: -c uname -a