name: Tester

on:
  push:
  pull_request:
  release:
    types: [published]

jobs:
  example2:
    runs-on: ubuntu-latest
    container:
      image: docker://turtlecoincore/ci:crypto-x64-linux
      options: --entrypoint /bin/bash
    steps:
      - name: Clone
        uses: actions/checkout@v2
        
      - name: Run Test
        run: |
          file /bin/bash
