name: Tester

on:
  push:
  pull_request:
  release:
    types: [published]

jobs:
  example2:
    runs-on: ubuntu-latest
    container:
      image: docker://turtlecoincore/ci:crypto-x64-linux
    steps:
      - uses: actions/checkout@v1
      - name: Run Test
        run: uname -a
